export const FETCH_DATA_START   = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const HEADER_TYPE = "HEADER_TYPE";